language: node_js
node_js:
  - '8'
## Cache NPM folder and Cypress binary
## to avoid downloading Cypress again and again
cache:
  yarn: true
  directories:
    - node_modules
    - ~/.npm
    - ~/.cache
install:
  - yarn
  - yarn global add codecov
script:
  - yarn test --coverage=true
  - codecov
  - yarn cypress:run

