name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup project
        run: npm ci

      - name: Build project
        run: npm run build --if-present

      - name: Unit Tests
        run: npm run test --coverage

      - name: Upload to codecov
        uses: codecov/codecov-action@v1

      - name: Cypress Tests
        uses: cypress-io/github-action@v2
        with:
          record: false
          start: npm run start
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Archive test videos
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: cypress-test-videos
          path: |
                cypress/videos/*.mp4

      - name: Archive test screenshots
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: cypress-test-screenshots
          path: |
                cypress/screenshots/*.png